import pandas as pd
df = pd.read_csv("student_performance.csv")
print(df)
print("\nDataset Information:")
print(df.info())
print("\nFirst 5 Records:")
print(df.head())
print("\nAverage Scores:")
print("Average Assignment Score:", df["Assignment Score"].mean())
print("Average Midterm Score:", df["Midterm Score"].mean())
print("Average Final Score:", df["Final Score"].mean()) 
print("\nHighest Scores:")
print("Highest Assignment Score:", df["Assignment Score"].max())
print("Highest Midterm Score:", df["Midterm Score"].max())
print("Highest Final Score:", df["Final Score"].max())
print("\nLowest Scores:")
print("Lowest Assignment Score:", df["Assignment Score"].min())
print("Lowest Midterm Score:", df["Midterm Score"].min())
print("Lowest Final Score:", df["Final Score"].min()) 
print("\nStudents with Attendance Below 75%:")
print(df[df["Attendance"] < 75][["Student Name", "Attendance"]])
print("\nStudents At Risk of Failing:")
print(df[df["Final Score"] < 60][["Student Name", "Final Score", "Attendance"]])
print("\nAverage Score by Course:")
print(df.groupby("Course")[["Assignment Score", "Midterm Score", "Final Score"]].mean())
print("\nRelationship between Attendance and Final Score:")
print(df[["Attendance", "Final Score"]].corr())
print("\nMissing Values:")
print(df.isnull().sum())
# Remove duplicate records
df = df.drop_duplicates()
# Fill missing numeric values with the column mean
numeric_columns = ["Age", "Attendance", "Assignment Score", "Midterm Score", "Final Score"]
for column in numeric_columns:
    df[column] = df[column].fillna(df[column].mean())
print("\nData after Cleaning:")
print(df.isnull().sum())
import matplotlib.pyplot as plt
# Chart 1: Score Distribution
plt.figure(figsize=(8, 5))
plt.hist(df["Final Score"], bins=8)
plt.xlabel("Final Score")
plt.ylabel("Number of Students")
plt.title("Final Score Distribution")
plt.savefig("chart1_score_distribution.png")
plt.close()
# Chart 2: Average Score by Course
course_avg = df.groupby("Course")["Final Score"].mean()
plt.figure(figsize=(8, 5))
course_avg.plot(kind="bar")
plt.xlabel("Course")
plt.ylabel("Average Final Score")
plt.title("Average Final Score by Course")
plt.savefig("chart2_average_score_by_course.png")
# Chart 3: Attendance vs Final Score
plt.figure(figsize=(8, 5))
plt.scatter(df["Attendance"], df["Final Score"])
plt.xlabel("Attendance")
plt.ylabel("Final Score")
plt.title("Attendance vs Final Score")
plt.savefig("chart3_attendance_vs_final_score.png")
plt.close()